---
title: "Write Yaml List from All Posts"
output: html_document
---

First, load some libraries that we'll need to write the YAML

```{r}
### This code reads through a set of files and parses out the YAML tags
### It then builds a yml list
### holy sweet awesomeness batman!
library(readr)
library(yaml)
library(dplyr)

```

Then setup the code to grab all .md files in the _posts directory and save the `authors.yml` file. 

```{r}
# avoid strings becoming factors
options(stringsAsFactors = FALSE)

# helper functions --------------------------------------------------------
generate_author_df <- function(file) {
  # extract "authors" field from yaml frontmatter
  # args:
  #   - file (string) a path to a markdown file with yaml frontmatter
  # returns:
  #   - data frame with a name and slug column, one row per author
  
  first_n_lines <- read_lines(file, n_max = 10) # should contain frontmatter
  author_line <- first_n_lines[grep("authors:", first_n_lines)]
  
  if (is.na(author_line[1])) {
    warning(paste("no authors for", file, "\n"))
    return(data.frame(name = NULL, slug = NULL))
  }
  
  # remove "authors: " and square brackets
  author_line <- gsub(pattern = "authors: ", x = author_line, replacement = "" )
  author_line <- gsub(pattern = "\\]|\\[", x = author_line, replacement = "" )
  
  # make a data frame with a row for each author
  df <- author_line %>%
    strsplit(split = ",") %>%
    unlist() %>%
    data.frame() 
  names(df) <- "name"
  
  # remove spaces and make lowercase: "Matt Oakley -> matt-oakley
  df %>%
    mutate(name = trimws(name), 
           slug = tolower(gsub(pattern = " ", x = name, replacement = "-"))) 
}



# produce the authors.yaml file -----------------------------------------
post_dir <- "../_posts"
md_files <- post_dir %>%
  file.path(list.files(post_dir, pattern = ".md", 
                           recursive = TRUE, include.dirs = TRUE))

# find all unique authors in the markdown files
authors <- lapply(md_files, generate_author_df) %>%
  do.call(what = rbind) %>%
  unique() %>%
  arrange(slug) 

finalYAML <- yaml::as.yaml(authors, column.major = FALSE)

# save output (do we need to prepend "_data/"?)
cat(finalYAML, file = "../_data/authors.yml")
```

Finally, for each author, save a markdown file that looks like: 

```
---
layout: post-by-author
author: Matt Oakley
permalink: /authors/matt-oakley/
title: 'Matt Oakley'
author_profile: false
site-map: true
---
```

```{r}
gen_author_profiles <- function(authors, prefix = "../org/authors") {
  # saves a markdown file for each author that will list their posts
  # args:
  #   - authors (data.frame consisting of the author name and slug)
  #   - prefix (string, specifying the destination directory for md files)
  # returns nothing
  for (i in 1:nrow(authors)) {
    # make a list with the name, layout, etc.
    auth_list <- list(layout = "post-by-author", 
                      author = authors$name[i], 
                      permalink = paste0("/authors/", authors$slug[i], "/"), 
                      title = authors$name[i], 
                      author_profile = "false",
                      `site-map` = "true")
    # convert to yaml
    auth_yaml <- as.yaml(auth_list)
    
    # save as md
    out_file <- paste0(paste0(authors$slug[i], ".md"))
    cat(paste0("----\n", 
               auth_yaml,
               "----\n"),
        file = file.path(prefix, out_file))
  }
}

gen_author_profiles(authors)
```
